// @ts-nocheck -- skip type checking
import * as docs_4 from "../content/docs/zh/index2.mdx?collection=docs&hash=1748168190319"
import * as docs_3 from "../content/docs/zh/index.mdx?collection=docs&hash=1748168190319"
import * as docs_2 from "../content/docs/en/index3.mdx?collection=docs&hash=1748168190319"
import * as docs_1 from "../content/docs/en/index2.mdx?collection=docs&hash=1748168190319"
import * as docs_0 from "../content/docs/en/index.mdx?collection=docs&hash=1748168190319"
import * as blogPosts_1 from "../content/blog/zh/hello.mdx?collection=blogPosts&hash=1748168190319"
import * as blogPosts_0 from "../content/blog/en/hello.mdx?collection=blogPosts&hash=1748168190319"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blogPosts = _runtime.doc<typeof _source.blogPosts>([{ info: {"path":"en/hello.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/blog/en/hello.mdx"}, data: blogPosts_0 }, { info: {"path":"zh/hello.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/blog/zh/hello.mdx"}, data: blogPosts_1 }]);
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"en/index.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/en/index.mdx"}, data: docs_0 }, { info: {"path":"en/index2.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/en/index2.mdx"}, data: docs_1 }, { info: {"path":"en/index3.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/en/index3.mdx"}, data: docs_2 }, { info: {"path":"zh/index.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/zh/index.mdx"}, data: docs_3 }, { info: {"path":"zh/index2.mdx","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/zh/index2.mdx"}, data: docs_4 }], [{"info":{"path":"en/meta.json","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/en/meta.json"},"data":{"title":"English","description":"ShipStack English Document","root":true,"icon":"LayoutGrid"}}, {"info":{"path":"zh/meta.json","absolutePath":"/Users/xu/Documents/Code/Indie/ShipStack/content/docs/zh/meta.json"},"data":{"title":"中文","description":"ShipStack 中文文档","root":true,"icon":"Palette"}}])