// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Header": {
    "locale": "English",
    "promotion_1": "If this project helps you, please give it a ⭐ on",
    "promotion_2": "Your support motivates us to keep improving."
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, zh {🇨🇳 简体中文} en {🇺🇸 English} other {Unknown}}"
  }
};
export default messages;